version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: demo_db
      POSTGRES_USER: demo_user
      POSTGRES_PASSWORD: 123456
    volumes:
      - ./odoo-data:/var/lib/odoo

  odoo:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - '8069:8069'
    environment:
      - PGUSER=demo_user
      - PGHOST=demo_db
      - PGPASSWORD=123456
      - PGDATABASE=demo_db
    volumes:
      - ./config:/etc/odoo

volumes:
  odoo-data:
  config:
